### ISSUE TITLE
Why no setup.py?

### ISSUE THREAD

**Issue by rafi** [tstringer/jersey#4]
The `setup.py` file is used by setuptools and among others allows installing via `pip install git+https://github.com/tstringer/jersey` or from a package at [PyPi](https://pypi.python.org/pypi).
The `Makefile` makes choices for the user which constraints the usage of envirtualenvs..

**Comment by trstringer** [comment]
I personally don't like to use setup.py/PyPI/pip for end-user applications. At that point, Python isn't an abstraction (end users shouldn't have to know what it is running under). Whereas I obviously agree that PyPI is perfect and appropriate for package consumption, for a CLI I'm not convinced it's the best user experience for setup.

With that being said, my Makefile is pretty broken right now in a couple of situations. I'm most likely going to transition this to a shell script or a python script for installation.

Finally, if you have a convincing argument to use PyPI for end user CLIs, I'd love to hear it! 😄
